# Generated by Django 5.0 on 2024-07-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=255)),
                ('department_name', models.CharField(max_length=255)),
                ('department_hod', models.CharField(max_length=255)),
                ('department_start', models.IntegerField()),
                ('department_student', models.IntegerField()),
            ],
        ),
    ]
