# Generated by Django 5.0 on 2024-07-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_library_alter_student_image_alter_student_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=255)),
                ('joining_date', models.DateField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
