# Generated by Django 5.0 on 2024-07-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('exam_class', models.CharField(max_length=255)),
                ('exam_subject', models.CharField(max_length=255)),
                ('exam_fees', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event_date', models.DateField()),
            ],
        ),
    ]
