# Generated by Django 5.0 on 2024-07-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_teacher_confirm_password_alter_teacher_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=155)),
                ('event_date', models.DateField()),
            ],
        ),
    ]
