# Generated by Django 5.0 on 2024-07-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_ebd_time_timetable_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='rating',
            field=models.BooleanField(default=False),
        ),
    ]
